### Preloads
GET http://localhost:3001/genre/pre HTTP/1.1
###
GET http://localhost:3001/platform/pre HTTP/1.1


### Show second data
GET http://localhost:3001/genre HTTP/1.1
###
GET http://localhost:3001/platform HTTP/1.1



###show main data
GET http://localhost:3001/videogame HTTP/1.1
### 
GET http://localhost:3001/videogame?name=evangelion HTTP/1.1
###
GET http://localhost:3001/videogame/3328 HTTP/1.1
###
GET http://localhost:3001/videogame/76b7070d-edee-4685-82d3-48d284601685 HTTP/1.1
###
POST http://localhost:3001/videogame HTTP/1.1
content-type: application/json

{
    "name": "Sample Game",
    "description": "Un juego ahi todo culero",
    "released": "2015-08-18",
    "rating": 4,
    "platforms": [7, 1],
    "genres": [4, 3],
    "image": "https://media.rawg.io/media/games/618/618c2031a07bbff6b4f611f10b6bcdbc.jpg"
} 